on:
  push:
    branches:
      - testing

name: Build
jobs:
  build:
    name: Build
    if: "!contains(github.event.head_commit.message, '[Build]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Console
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: INIT WORKFLOW - Dispatch init event to other repository workflow
        run: |
          curl -X POST https://api.github.com/repos/GuillaumeFalourd/actions-download-file/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.GITHUB_TOKEN }} \
          --data '{"event_type": "Start Download", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
