on:
  push:
    branches:
      - testing

name: Build
jobs:
  build:
    name: Build
    if: "!contains(github.event.head_commit.message, '[Build]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Console
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Commit and Push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git status
          git add .
          git status
          git commit -m "[Build]" -a --allow-empty
          git push origin ${{ github.ref }}
