on:
  push:
    branches:
      - testing

name: Build
jobs:
  build:
    name: Build
    if: "!contains(github.event.head_commit.message, '[Build]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Console
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: GuillaumeFalourd/actions-download-file
          event-type: to-download
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'