name: Testing

on:
  push:
    branches:
      - testing

jobs:
  test_the_action:
    if: contains(github.event.head_commit.message, '[Build]')
    name: Test the action
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: angelk90/actions-download-file@master
        id: downloadfile
        name: Download a file
        with:
          url: "[API Endpoint](https://api.github.com/repos/suisei-cn/actions-download-file)"
          target: public/

      - name: Console
        run: echo "$GITHUB_CONTEXT"
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Display the file
        run: head -n8 public/actions-download-file
